spring:
  config:
    activate:
      on-profile: dev
name: fhir-client-udap-demo-dev
environment: development
enabled: true
fhir-client-default: Dev FHIR Client
fhir-clients:
   -
      # Nick name is short reference identifer to locate client in list
      client-nickname: Dev FHIR Client
      
      ############################################
      # UDAP Client Software Statement Defaults
      ############################################
      client-name: FHIR UDAP Client (Springboot)
      redirect-uris: ~
      contacts:
         - 'mailto:bstring.slc@gmail.com'
      logoUri: https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png
      grant-types:
         - client_credentials
      scopes:
         - system/Patient.read
         - system/Procedures.read
      response-types: ~
      token-endpoint-auth-method: private_key_jwt
      ##########
      
      # STU1 - SHALL be no more than 5 minutes (expressed in seconds)
      software-statement-ttl: 300
      
      # STU1 - SHALL be not more than 5 miutes (expressed in seconds)
      auth-n-token-ttl: 300
      
      # Populated if this client has already been registered with the authorization server
      client-id: ${UDAP_FHIR_CLIENT_ID} 
      
      # Clients x509 Certificate Location
      x509-location: ${UDAP_FHIR_CLIENT_X509_LOCATION}
      
      # Client's Private key location
      private-key-location: ${UDAP_FHIR_CLIENT_PRIVATE_KEY_LOCATION}
      
      # Client's Private Key Secret
      # In a production scenario such secrets would be handled by some vaulting mechanism
      private-key-secret: ${UDAP_FHIR_CLIENT_PRIVATE_KEY_SECRET}    